# Blunderbuss config
assign_issues:
  - googleapis/cloud-sdk-python-team
  - googleapis/bigquery-dataframe-team

assign_issues_by:
  - labels:
      - "samples"
    to:
      - googleapis/python-samples-reviewers
      - googleapis/cloud-sdk-python-team
      - googleapis/bigquery-dataframe-team

assign_prs:
  - googleapis/cloud-sdk-python-team
  - googleapis/bigquery-dataframe-team
